import Head from 'next/head'

import { Inter } from '@next/font/google'
import LivroLista from './dados/LivroLista'
import MyModal from './modelo/testes'
const inter = Inter({ subsets: ['latin'] })
 import LivroDados from './dados/Livrodados'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
      <main className="styles.main">
        <h1 className="styles.title">Página Inicial</h1>
      </main>
        
        
      </main>
    </>
  )
}
